name: CI

on: [push, pull_request]

jobs:

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.17
    - uses: actions/checkout@v1
    - name: Build and test
      shell: pwsh
      run: ./build-and-test.ps1
